CURRENT_DIR := $(lastword $(shell basename $(CURDIR)))

all: build/$(CURRENT_DIR).pdf

# hier Python-Skripte:
build/advanced_curves.pdf: plot.py ../matplotlibrc ../header-matplotlib.tex | build
	# so that matplotlib can find the tex header when running
	# LaTeX in the tmp directory
	# and set the matplotlibrc
	TEXINPUTS=$$(pwd)/..: MATPLOTLIBRC=../matplotlibrc python plot.py

# hier weitere Abhängigkeiten für build/vXXX.pdf deklarieren:
build/$(CURRENT_DIR).pdf: build/advanced_curves.pdf

build/$(CURRENT_DIR).pdf: FORCE | build
	# to find header and bib files in the main directory
	TEXINPUTS=..: \
	BIBINPUTS=..: \
	max_print_line=1048576 \
	latexmk \
	  --lualatex \
	  --output-directory=build \
	  --interaction=nonstopmode \
	  --halt-on-error \
	$(CURRENT_DIR).tex

only_doc:
	# to find header and bib files in the main directory
	TEXINPUTS=..: \
	BIBINPUTS=..: \
	max_print_line=1048576 \
	latexmk \
	  --lualatex \
	  --output-directory=build \
	  --interaction=nonstopmode \
	  --halt-on-error \
	$(CURRENT_DIR).tex

build:
	mkdir -p build

clean:
	rm -rf build

FORCE:

.PHONY: all clean
